# Introduction to word embeddings and Keras

In [1]:
# tutorial from 
# https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/

In [123]:
import numpy as np
from keras.preprocessing.text import one_hot
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [7]:
# our documents
docs = ['Well done!', 'Good work', 'Great effort', 'nice work',
       'Excellent!', 'Weak', 'Poor effort!', 'not good', 'poor work',
       'Could have done better.']

# define class labels
labels = np.array([1,1,1,1,1,0,0,0,0,0])

In [138]:
vocab_size = 50
print len(set(reduce(lambda x,y: x+y, [d.split() for d in docs] )))

# integer encode the documents
#encoded_docs = [one_hot(d, vocab_size) for d in docs]
#print encoded_docs

# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)
print(encoded_docs)

# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print padded_docs


18
[[6, 2], [3, 1], [7, 4], [8, 1], [9], [10], [5, 4], [11, 3], [5, 1], [12, 13, 2, 14]]
[[ 6  2  0  0]
 [ 3  1  0  0]
 [ 7  4  0  0]
 [ 8  1  0  0]
 [ 9  0  0  0]
 [10  0  0  0]
 [ 5  4  0  0]
 [11  3  0  0]
 [ 5  1  0  0]
 [12 13  2 14]]


In [143]:
t.word_index

{'better': 14,
 'could': 12,
 'done': 2,
 'effort': 4,
 'excellent': 9,
 'good': 3,
 'great': 7,
 'have': 13,
 'nice': 8,
 'not': 11,
 'poor': 5,
 'weak': 10,
 'well': 6,
 'work': 1}

In [139]:
# define the model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

# summarise the model
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_13 (Embedding)     (None, 4, 8)              120       
_________________________________________________________________
flatten_12 (Flatten)         (None, 32)                0         
_________________________________________________________________
dense_12 (Dense)             (None, 1)                 33        
Total params: 153
Trainable params: 153
Non-trainable params: 0
_________________________________________________________________


In [144]:
# fit the model
model.fit(padded_docs, labels, epochs=10, verbose=0)


In [145]:
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print loss, accuracy

0.5790029168128967 1.0


In [88]:
# create BoW representation
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
bag = cv.fit_transform(docs)
bag.toarray()
len(cv.vocabulary_)

14