In [2]:
import numpy as np
from numpy.linalg import norm

In [51]:
a = np.array([[1,2,3],[4,5,6]])
print a
print norm(a)

b = (np.arange(6) + 1).reshape((2,3))
print b
print norm(b)

print "-"*30
c = np.array([1,2,3,4,5,6])
print c
print norm(c)

d = c.reshape((2,3))
print d
print norm(d)




[[1 2 3]
 [4 5 6]]
9.539392014169456
[[1 2 3]
 [4 5 6]]
9.539392014169456
------------------------------
[1 2 3 4 5 6]
9.539392014169456
[[1 2 3]
 [4 5 6]]
9.539392014169456


In [32]:
a = np.arange(8) - 4
print a
print norm(a)

b = a.reshape((2, 4))
print b
print norm(b)


a = np.arange(8) + 1
print a
print norm(a)

b = a.reshape((2, 4))
print b
print norm(b)



[-4 -3 -2 -1  0  1  2  3]
6.6332495807108
[[-4 -3 -2 -1]
 [ 0  1  2  3]]
6.6332495807108
[1 2 3 4 5 6 7 8]
14.2828568570857
[[1 2 3 4]
 [5 6 7 8]]
14.2828568570857


In [50]:
np.sqrt(np.sum(a**2))

9.539392014169456

In [78]:
a = np.array([[1],[2],[3]])
b = np.array([1,2,3])
#print a.T, b

np.dot(a.T,b)

a = np.random.randint(5, size=(5,2))
b = np.random.randint(5, size=(2, 4))
print a
print b

[[3 1]
 [1 3]
 [2 4]
 [1 4]
 [3 4]]
[[0 2 4 0]
 [2 1 1 4]]
