In [1]:
import numpy as np

In [2]:
timesteps = 100
input_features = 32
output_features = 64


In [3]:
inputs = np.random.random((timesteps, input_features))
state_t = np.zeros((output_features,))

In [4]:
W = np.random.random((output_features, input_features))
U = np.random.random((output_features, output_features))
b = np.random.random((output_features,))

In [5]:
successive_outputs = []

In [6]:
for input_t in inputs:
    output_t = np.tanh(np.dot(W, input_t) + np.dot(U, state_t) + b)
    successive_outputs.append(output_t)
    state_t = output_t

final_output_sequence = np.concatenate(successive_outputs, axis=0)

In [35]:
print W.shape, input_t.shape

#np.dot(W, input_t)
np.dot(U, state_t)

(64, 32) (32,)


array([32.94672185, 28.04465784, 32.7306616 , 29.67354101, 31.3149295 ,
       31.7420707 , 24.86971591, 32.69690627, 31.27905897, 33.34365516,
       28.43031107, 34.4288987 , 28.67409144, 32.95734193, 32.57006649,
       30.49717169, 34.27802665, 30.05584663, 28.15041504, 28.82076105,
       28.89436343, 30.9491869 , 32.94554055, 28.38293764, 28.04877461,
       33.22372616, 31.14392857, 28.19309376, 30.68734755, 29.9897611 ,
       32.27239898, 31.89900086, 31.41283556, 33.19588092, 28.41038892,
       33.70203953, 34.71286216, 28.79659208, 30.31653212, 27.96133947,
       33.05008846, 32.4559182 , 34.51603637, 29.93021866, 31.01053612,
       28.84297185, 33.85652175, 30.29340836, 34.4159106 , 31.51442274,
       35.15661371, 33.57303262, 32.83875893, 31.34929351, 34.18667725,
       32.24154389, 33.90559547, 29.27470881, 33.19869269, 33.74322646,
       31.3226925 , 31.18934171, 32.30191099, 31.9567667 ])

In [215]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import normalize

np.random.seed(420)

hypo_vsm = np.random.randint(100, size=(100, 20)) * np.random.randint(2, size=(100,20))
hyper_vsm = np.random.randint(100, size=(100, 20)) * np.random.randint(2, size=(100,20))

hypo_vsm_l2 = normalize(hypo_vsm)
hyper_vsm_l2 = normalize(hyper_vsm)

features = np.hstack((hypo_vsm_l2 - hyper_vsm_l2, np.square(hyper_vsm_l2 - hypo_vsm_l2)))

y = np.concatenate((np.zeros(50), np.ones(50)))

lr = LogisticRegression(random_state = 0,  max_iter=100)
lr.fit(features, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [211]:
features[0]

array([ 0.00000000e+00,  9.68470658e-03,  2.27944053e-01,  0.00000000e+00,
        0.00000000e+00, -1.09935593e-01,  1.07308339e-01,  0.00000000e+00,
       -2.38990419e-02, -1.72073102e-01,  6.98039987e-02,  3.08803885e-02,
       -2.40493546e-02, -8.36466467e-02,  2.02667999e-01,  0.00000000e+00,
        1.13742244e-01,  1.76932380e-01,  0.00000000e+00, -2.96089094e-02,
       -1.97674382e-01,  4.36586392e-02, -1.64903389e-01, -2.47784363e-02,
        3.14801767e-02,  9.49000946e-02,  2.10203513e-01,  2.94121359e-02,
        8.73628985e-02,  5.21605847e-02,  1.28447471e-01,  1.61219743e-02,
       -1.50563964e-01, -1.84022623e-01, -2.47801178e-02,  1.40167210e-01,
       -5.49677964e-02,  1.56251972e-02, -1.91192335e-02,  0.00000000e+00,
        2.16225155e-01, -1.24275018e-01, -2.10311569e-01, -9.03626799e-02,
       -8.80225997e-02,  2.75738774e-02,  0.00000000e+00,  0.00000000e+00,
        7.66070685e-02,  0.00000000e+00, -1.93118033e-02,  2.13467767e-01,
       -1.60494427e-01,  

In [216]:
from sklearn.model_selection import cross_val_score

cross_val_score(lr, features, y, cv=5, scoring='f1')

array([0.5       , 0.55555556, 0.375     , 0.52631579, 0.76923077])

In [217]:
print np.round(lr.coef_[0], 5)
print np.round(lr.coef_[0][:20], 5) 

print np.argsort(lr.coef_[0][:20])+1

print "-"*50
print np.round(lr.coef_[0][20:], 5) 
print np.argsort(lr.coef_[0][20:])+1

[-0.16798 -0.15616 -0.04371 -0.48902 -0.95529  0.33397  0.37092 -0.19768
  1.20869  0.66214 -0.96481  0.74859 -0.47738 -0.73588 -0.11022 -0.71014
  0.32191 -0.31912 -0.01832  0.29059 -0.32263  0.1771   0.3934   0.26988
 -0.1233   0.43572 -0.75685 -0.29979 -0.14421 -0.1242   0.24377  0.2939
  0.07324  0.14653 -0.15842 -0.18081  0.0507  -0.50926 -0.15242  0.04022]
[-0.16798 -0.15616 -0.04371 -0.48902 -0.95529  0.33397  0.37092 -0.19768
  1.20869  0.66214 -0.96481  0.74859 -0.47738 -0.73588 -0.11022 -0.71014
  0.32191 -0.31912 -0.01832  0.29059]
[11  5 14 16  4 13 18  8  1  2 15  3 19 20 17  6  7 10 12  9]
--------------------------------------------------
[-0.32263  0.1771   0.3934   0.26988 -0.1233   0.43572 -0.75685 -0.29979
 -0.14421 -0.1242   0.24377  0.2939   0.07324  0.14653 -0.15842 -0.18081
  0.0507  -0.50926 -0.15242  0.04022]
[ 7 18  1  8 16 15 19  9 10  5 20 17 13 14  2 11  4 12  3  6]


In [220]:
np.dot(lr.coef_[0], features[50])

1.0600100637330936

In [109]:
t1 = np.arange(5)
t2 = np.arange(5,10)

t1 - t2
t2 - t1

array([5, 5, 5, 5, 5])

In [226]:
for i in range(100):
    print hypo_vsm[i,10], hyper_vsm[i, 10], y[i]


23 18 0.0
5 50 0.0
60 0 0.0
43 0 0.0
0 0 0.0
0 0 0.0
0 8 0.0
0 0 0.0
0 63 0.0
46 98 0.0
0 0 0.0
0 0 0.0
1 86 0.0
0 0 0.0
88 54 0.0
0 73 0.0
0 80 0.0
0 0 0.0
0 0 0.0
0 49 0.0
0 0 0.0
0 31 0.0
0 23 0.0
20 60 0.0
87 0 0.0
0 91 0.0
48 23 0.0
0 3 0.0
0 0 0.0
70 23 0.0
42 57 0.0
23 0 0.0
0 63 0.0
11 0 0.0
59 99 0.0
0 25 0.0
0 0 0.0
0 0 0.0
48 53 0.0
0 3 0.0
0 15 0.0
0 0 0.0
84 80 0.0
12 17 0.0
0 3 0.0
98 43 0.0
51 88 0.0
0 19 0.0
75 68 0.0
0 0 0.0
0 22 1.0
43 0 1.0
92 0 1.0
0 0 1.0
0 41 1.0
95 0 1.0
0 0 1.0
4 0 1.0
95 35 1.0
34 0 1.0
0 48 1.0
30 71 1.0
0 16 1.0
0 0 1.0
4 61 1.0
29 80 1.0
28 0 1.0
0 87 1.0
0 0 1.0
0 0 1.0
83 0 1.0
0 63 1.0
0 80 1.0
0 54 1.0
0 43 1.0
0 0 1.0
0 0 1.0
40 0 1.0
63 27 1.0
3 48 1.0
96 21 1.0
0 20 1.0
0 0 1.0
84 65 1.0
66 51 1.0
0 2 1.0
61 70 1.0
85 0 1.0
54 0 1.0
0 50 1.0
54 3 1.0
39 4 1.0
16 0 1.0
0 88 1.0
0 0 1.0
60 72 1.0
39 0 1.0
21 0 1.0
87 0 1.0
0 0 1.0
